import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./fireworks.scss";

import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="pyro">
          <div className="before"></div>
          <div className="after"></div>
        </div>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
